on:
  push:
jobs:
  lint-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: install packages
        run: npm install 
      - name: Image prohibit
        run: ./prohibit_image_files.sh origin/master HEAD 
      - name: run audit
        run: npm audit --audit-level critical 
      - name: run lint
        run: npm run-script lint:ci
      - name: run unit
        run: npm run-script test:unit:ci
      - name: run e2e
        run: npm run-script test:e2e:ci
  accessibility:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: install packages
        run: npm install 
      - name: run accessibility
        run: npm run-script test:accessibility:ci
  # visual:
  #    runs-on: ubuntu-latest
  #    steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: '12'
  #     - name: install packages
  #       run: npm install 
  #     - name: checkout-lfs
  #       run: git lfs pull
  #     - name: run visual
  #       run: npm run test:visual
  #     - name: upload fails
  #       uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: broken images 
  #         path: /home/runner/work/developer-portal/developer-portal/test/image_snapshots/__diff_output__/*.png 
  build:
     runs-on: ubuntu-latest
     needs: [ visual, accessibility, lint-unit]
     env:
       BUILD_ENV: dev
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: install packages
        run: npm install 
      - name: build
        run: npm run-script build $BUILD_ENV
      - name: tar build
        run: tar -C build/${BUILD_ENV} -cf build/${GITHUB_SHA}.tar.bz2 .
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/${{ env.GITHUB_SHA  }}.tar.bz2
