on:
  push:
jobs:
  lint-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build --target ci -t devportal .
      - name: Image prohibit
        run: ./prohibit_image_files.sh origin/master HEAD 
      - name: run audit
        run: docker run --name audit -t devportal npm audit --audit-level critical 
      - name: run lint
        run: docker run --name lint -t devportal npm run-script lint:ci
      - name: run unit
        run: docker run --name unit -t devportal npm run-script test:unit:ci
      - name: run e2e
        run: docker run --name e2e -t devportal npm run-script test:e2e:ci
  accessibility:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build --target ci -t devportal .
      - name: run accessibility
        run: docker run --name accessibility -t devportal npm run-script test:accessibility:ci
  visual:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: git-lfs
        run: git lfs pull
      - name: Build container
        run: docker build --target ci -t devportal .
      - name: run visual
        run: docker run --name visual devportal npm run test:visual
  #     - name: upload fails
  #       uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: broken images 
  #         path: /home/runner/work/developer-portal/developer-portal/test/image_snapshots/__diff_output__/*.png 
  build:
     runs-on: ubuntu-latest
     needs: [ accessibility, lint-unit, visual ]
     env:
       BUILD_ENV: dev
     steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build --target ci -t devportal .
      - name: build
        run: docker run --name build -t devportal npm run-script build $BUILD_ENV
      - name: cp
        run: docker cp build:application/build/${BUILD_ENV} .
      - name: tar build
        run: tar -C ${BUILD_ENV} -cf test.tar.bz2 .
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: test.tar.bz2
